services:
  - type: web
    name: n8n-cloud
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: sanrasta
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Bogota11!!
      - key: N8N_AUTH_EXCLUDE_ENDPOINTS
        value: '*'
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: 'true'
